{{$ssh_username := .Model.MustVariable "credentials.ssh.username"}}
{{$identity := .Component.PublicIdentity}}
{{$ctrl_ip := publicIp "component#ctrl"}}
{{$router_ip := .Host.PublicIp}}
  
v: 3

enableDebugOps: true

identity:
  cert:                 /home/{{$ssh_username}}/fablab/pki/intermediate/certs/{{$identity}}-client.cert
  server_cert:          /home/{{$ssh_username}}/fablab/pki/intermediate/certs/{{$identity}}-server.cert
  key:                  /home/{{$ssh_username}}/fablab/pki/intermediate/keys/{{$identity}}.key
  ca:                   /home/{{$ssh_username}}/fablab/pki/intermediate/certs/{{$identity}}-server.chain.pem

ctrl:
  endpoint:             tls:{{$ctrl_ip}}:6262

healthChecks:
  ctrlPingCheck:
    # How often to ping the controller over the control channel. Defaults to 30 seconds
    interval: 30s
    # When to timeout the ping. Defaults to 15 seconds
    timeout: 15s
    # How long to wait before pinging the controller. Defaults to 15 seconds
    initialDelay: 15s

metrics:
  reportInterval: 15s
  messageQueueSize: 10

link:
  listeners:
    - binding:          transport
      bind:             tls:0.0.0.0:6000
      advertise:        tls:{{$router_ip}}:6000
  dialers:
    - binding:          transport

listeners:
{{if .Component.HasTag "tunneler"}}
  - binding: tunnel
    options:
      mode: tproxy
{{end}}
  - binding: edge
    address: tls:0.0.0.0:6262
    options:
      # (required) The public hostname and port combination that Ziti SDKs should connect on. Previously this was in the chanIngress section.
      advertise: {{ .Host.PublicIp }}:6262

# By having an 'edge' section defined, the ziti-router will attempt to parse the edge configuration. Removing this
# section, commenting out, or altering the name of the section will cause the router to no longer operate as an Edge
# Router.
edge:
  # (required) Information used to generate the initial registration CSR. For documentation on these fields please
  # refer to the openssl documentation. These values MUST be supplied and have no defaults.
  csr:
    country: US
    province: NC
    locality: Charlotte
    organization: NetFoundry
    organizationalUnit: Ziti

    # (required) SANs that this Gateways certs should contain. At least one IP or DNS SAN should be defined that matches
    # the edge listeners "advertise" value from the "listeners" section.
    sans:
      ip:
        - {{ .Host.PublicIp }}

