{{$ssh_username := .Model.MustVariable "credentials.ssh.username"}}
{{$identity := .Component.PublicIdentity}}
{{$protocol := .Model.MustVariable "zitilib.fabric.data_plane_protocol"}}
{{$ctrl_ip := publicIp "component.ctrl"}}
{{$router_ip := .Host.PublicIp}}
  
v: 3

forwarder:
  latencyProbeInterval: 1000

identity:
  cert:                 /home/{{$ssh_username}}/fablab/pki/intermediate/certs/{{$identity}}-client.cert
  server_cert:          /home/{{$ssh_username}}/fablab/pki/intermediate/certs/{{$identity}}-server.cert
  key:                  /home/{{$ssh_username}}/fablab/pki/intermediate/keys/{{$identity}}.key
  ca:                   /home/{{$ssh_username}}/fablab/pki/intermediate/certs/{{$identity}}-server.chain.pem

ctrl:
  endpoint:             tls:{{$ctrl_ip}}:6262

listeners:
  - binding:            proxy
    address:            tcp:0.0.0.0:7001
    service:            iperf

  - binding:            proxy_udp
    address:            udp:0.0.0.0:7001
    service:            iperf_udp

  - binding:            transport
    address:            tls:0.0.0.0:7002

dialers:
  - binding:            transport

link:
  listeners:
    - binding:          transport
      bind:             {{$protocol}}:0.0.0.0:6000
      advertise:        {{$protocol}}:{{$router_ip}}:6000
  dialers:
    - binding:          transport
